import { CommuneConfig } from './types';

export const WMS_URL = 'https://www4.sii.cl/mapasui/services/ui/wmsProxyService/call?';
export const WORKER_URL = 'https://sii-proxy.javierb1820.workers.dev';

export const COMUNAS_CONFIG: CommuneConfig[] = [
  { name: "Las Condes", code: 15108, layerName: "sii:BR_CART_LAS_CONDES_WMS" },
  { name: "Vitacura", code: 15160, layerName: "sii:BR_CART_VITACURA_WMS" },
  { name: "Lo Barnechea", code: 15161, layerName: "sii:BR_CART_LO_BARNECHEA_WMS" },
  { name: "Providencia", code: 15103, layerName: "sii:BR_CART_PROVIDENCIA_WMS" },
  { name: "La Reina", code: 15132, layerName: "sii:BR_CART_LA_REINA_WMS" },
  { name: "Ñuñoa", code: 15105, layerName: "sii:BR_CART_NUNOA_WMS" },
  { name: "Recoleta", code: 13159, layerName: "sii:BR_CART_RECOLETA_WMS" },
  { name: "Independencia", code: 13167, layerName: "sii:BR_CART_INDEPENDENCIA_WMS"},
  { name: "Santiago Centro", code: 13101, layerName: "sii:BR_CART_SANTIAGO_CENTRO_WMS" },
  { name: "Santiago Oeste", code: 13134, layerName: "sii:BR_CART_SANTIAGO_OESTE_WMS" },
  { name: "Santiago Sur", code: 13135, layerName: "sii:BR_CART_SANTIAGO_SUR_WMS" },
  { name: "Estación Central", code: 14157, layerName: "sii:BR_CART_ESTACION_CENTRAL_WMS" },
  { name: "Lo Prado", code: 14155, layerName: "sii:BR_CART_LO_PRADO_WMS" },
  { name: "Pudahuel", code: 14111, layerName: "sii:BR_CART_PUDAHUEL_WMS" },
  { name: "Quinta Normal", code: 14107, layerName: "sii:BR_CART_QUINTA_NORMAL_WMS" },
  { name: "Cerro Navia", code: 14156, layerName: "sii:BR_CART_CERRO_NAVIA_WMS" },
  { name: "Renca", code: 14113, layerName: "sii:BR_CART_RENCA_WMS" },
  { name: "Lampa", code: 14202, layerName: "sii:BR_CART_LAMPA_WMS" },
  { name: "Til Til", code: 14203, layerName: "sii:BR_CART_TIL_TIL_WMS" },
  { name: "Melipilla", code: 14601, layerName: "sii:BR_CART_MELIPILLA_WMS" },
  { name: "María Pinto", code: 14602, layerName: "sii:BR_CART_MARIA_PINTO_WMS" },
  { name: "Curacaví", code: 14603, layerName: "sii:BR_CART_CURACAVI_WMS" },
  { name: "El Monte", code: 14503, layerName: "sii:BR_CART_EL_MONTE_WMS" },
  { name: "Padre Hurtado", code: 14505, layerName: "sii:BR_CART_PADRE_HURTADO_WMS" },
  { name: "San Joaquín", code: 16163, layerName: "sii:BR_CART_SAN_JOAQUIN_WMS" },
  { name: "San Miguel", code: 16106, layerName: "sii:BR_CART_SAN_MIGUEL_WMS" },
  { name: "Pedro Aguirre Cerda", code: 16162, layerName: "sii:BR_CART_P_AGUIRRE_CERDA_WMS" },
  { name: "Cerrillos", code: 14166, layerName: "sii:BR_CART_CERRILLOS_WMS" },
  { name: "Maipú", code: 14109, layerName: "sii:BR_CART_MAIPU_WMS" },
  { name: "La Granja", code: 16131, layerName: "sii:BR_CART_LA_GRANJA_WMS" },
  { name: "La Cisterna", code: 16110, layerName: "sii:BR_CART_LA_CISTERNA_WMS" },
  { name: "Lo Espejo", code: 16164, layerName: "sii:BR_CART_LO_ESPEJO_WMS" },
  { name: "La Pintana", code: 16154, layerName: "sii:BR_CART_LA_PINTANA_WMS" },
  { name: "El Bosque", code: 16165, layerName: "sii:BR_CART_EL_BOSQUE_WMS" },
  { name: "San Bernardo", code: 16401, layerName: "sii:BR_CART_SAN_BERNARDO_WMS" },
  { name: "Huechuraba", code: 14158, layerName: "sii:BR_CART_HUECHURABA_WMS" },
  { name: "Quilicura", code: 14114, layerName: "sii:BR_CART_QUILICURA_WMS" },
  { name: "Conchalí", code: 14127, layerName: "sii:BR_CART_CONCHALI_WMS" },
  { name: "Macul", code: 15151, layerName: "sii:BR_CART_MACUL_WMS" },
  { name: "Peñalolén", code: 15152, layerName: "sii:BR_CART_PENALOLEN_WMS" },
  { name: "La Florida", code: 15128, layerName: "sii:BR_CART_LA_FLORIDA_WMS" },
  { name: "Puente Alto", code: 16301, layerName: "sii:BR_CART_PUENTE_ALTO_WMS" },
  { name: "Pirque", code: 16302, layerName: "sii:BR_CART_PIRQUE_WMS" },
  { name: "San José de Maipo", code: 16303, layerName: "sii:BR_CART_SAN_JOSE_MAIPO_WMS" }
];